-- Migration number: 0003 	 2024-03-07T15:00:55.144Z
CREATE TABLE IF NOT EXISTS refresh_tokens (
	id TEXT NOT NULL PRIMARY KEY,
	user_id TEXT NOT NULL,
	token VARCHAR(36) NOT NULL,
	issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expires_at TIMESTAMP NOT NULL,
	FOREIGN KEY (user_id) REFERENCES user(id)
);
