name: Rotate JWT Keys

on:
  workflow_dispatch:
  schedule:
    # Run this workflow every Monday at 00:00 UTC
    - cron: '0 0 * * 1'

jobs:
  rotate-keys:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Generate new key pair
      run: |
        openssl genpkey -algorithm RSA -out private.pem -pkeyopt rsa_keygen_bits:2048
        openssl rsa -pubout -in private.pem -out public.pem

    - name: Install Wrangler
      run: npm install -g @cloudflare/wrangler

    - name: Update private key in Cloudflare Worker as secret
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        wrangler secret put PRIVATE_KEY < private.pem
        rm private.pem

    - name: Update public key in Cloudflare Worker as secret
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        wrangler secret put PUBLIC_KEY < public.pem
        rm public.pem
